import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/models/contexts/theme-context"
import { Header } from "@/views/includes/header/header"
import { ContactForm } from "@/views/components/contact-form"
import { SERVICES, TEAM_MEMBERS, SITE_VERSION } from "@/models/lib/constants"
import { GrapeIcon as Grass, Users, Info, Phone, Flower, TreesIcon as Tree, Droplet } from "lucide-react"
import Image from "next/image"
import { CustomCursor } from "@/views/components/custom-cursor"
import { AIHelp } from "@/views/components/ai-help"
import { MultiStepForm } from "@/views/components/multi-step-form"
import "./globals.css";
import { Footer } from "@/views/includes/footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "A Tidy Lawn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-white dark:bg-gray-900 font-thin cursor-none`}
      >
        <ThemeProvider>
        <CustomCursor />
    <AIHelp />

              <Header />
          
        {children}

<Footer/>
        </ThemeProvider>

      </body>
    </html>
  );
}
